<p>{{ content() }}</p>
<?php $date = new DateTime(); ?>
<div>
    <?php if (isset($category_id)) { ?>
        <div class="title">Изменить закупку товаров</div>
    <?php } else { ?>
        <div class="title">Добавить закупку товаров</div>
    <?php } ?>
    {{ form('/categories/save', 'id' : 'new_category_form', 'enctype' : 'multipart/form-data', 'class' : 'form-horizontal') }}
        <table class="table table-bordered table-condensed">
            <tr>
                <td><label for="category_title">Название:</label></td>
                <td>
                    {{ text_field("category_title", 'required' : '', 'class' : 'form-control') }}
                </td>
            </tr>
            <tr>
                <td><label for="category_description">Описание:</label></td>
                <td>
                    {{ text_area("category_description", 'class' : 'form-control', 'rows' : 15) }}
                </td>
            </tr>
            <tr>
                <td><label for="category_stopdatetime">Дата стопа:</label></td>
                <td>
                    <div class="input-append date" id="datetimepicker" data-date="<?= (isset($stop_datetime) ? $stop_datetime->format('d.m.Y H:00') : $date->format('d.m.Y H:00')) ?>" data-date-format="dd.mm.yyyy" date-language='ru'>
                        <input class="controls1" size="16" type="text" value="<?= (isset($stop_datetime) ? $stop_datetime->format('d.m.Y H:00') : $date->format('d.m.Y H:00')) ?>" name='category_stop_datetime' required="">
                        <span class="add-on"><i class="icon-calendar"></i></span>
                    </div> 
                </td>
            </tr>
            <?php if (isset($category_id)) { ?>
            <tr>
                <td><label for="update_datetime">В начало списка:</label></td>
                <td>
                    {{ check_field("update_datetime") }}
                </td>
            </tr>
            <?php } ?>
            <tr>
                <td><label for="category_hidden">Не показывать клиентам:</label></td>
                <td>
                    {{ check_field("category_hidden") }}
                </td>
            </tr>
            <tr>
                <td><label for="category_use_forum">Разрешить обсуждение:</label></td>
                <td>
                    {{ check_field("category_use_forum") }}
                </td>
            </tr>
            <tr>
                <td><label for="category_parent_id">Родительская категория:</label></td>
                <td>
                    {{ select("category_parent_id", parents, 'using' : ['id', 'title'], 'useEmpty' : true, 'emptyText' : '-', 'class' : 'form-control' ) }}
                </td>
            </tr>
            <tr>
                <td><label for="category_rules">Условия закупки:</label></td>
                <td>
                    {{ text_area("category_rules", 'class' : 'form-control', 'rows' : 15) }}
                </td>
            </tr>
            <tr>
                <td><label for="category_photo">Изображение:</label></td>
                <td>
                    {{ file_field("category_photo", 'onchange' : 'removePhoto(); return false;') }}
                </td>
            </tr>
            <?php if (isset($category_id) && strlen($category_img)) { ?>
            <tr id='img_row'>
                <td class="cat_title">
                    {{ link_to('#', 'onclick' : 'removePhoto(); return false;', 'class' : "btn btn-warning", 'text' : 'Удалить изображение') }}
                </td>
                <td>
                    <div>
                        <img id='cat_img' class="cat_img" src="data:image/jpeg;charset=utf-8;base64,<?= $category_img ?>">
                    </div>
                    
                </td>
            </tr>
            <?php } ?>
        </table>
        
        <div class="control-group">
            <div class="controls">
        <?php if (isset($category_id)) { ?>
            {{ submit_button("Обновить", 'name' : 'update_category', 'class' : 'btn btn-lg btn-primary btn-block') }}
            
            {{ submit_button("В новую закупку", 'name' : 'clone_category', 'class' : 'btn btn-lg btn-primary btn-block') }}
            
            {{ hidden_field("category_id", 'value' : category_id) }}
            {{ hidden_field("category_img", 'value' : category_img) }}
        <?php } else { ?>
            {{ submit_button("Добавить", 'name' : 'add_category', 'class' : 'btn btn-lg btn-primary btn-block') }}
        <?php } ?>
            </div>
        </div>
        
    </form>
</div>
<script>
    <!--
    $(document).ready(function () {
        $("#datetimepicker").datetimepicker({
            format: 'dd.mm.yyyy hh:ii',
            autoclose: true,
            todayBtn: true,
            pickerPosition: "bottom-left",  
            language: 'ru',
            weekStart: 1
        });
    });
    
    function removePhoto() {
        $('#img_row').remove();
        $('#category_img').remove();
    }
    -->
</script>