<p>{{ content() }}</p>
<?php $date = new DateTime(); ?>
<div>
    <?php if (isset($category_id)) { ?>
        <div class="title">Изменить закупку товаров</div>
    <?php } else { ?>
        <div class="title">Добавить закупку товаров</div>
    <?php } ?>
    {{ form('/categories/save', 'id' : 'new_category_form', 'enctype' : 'multipart/form-data', 'class' : 'form-horizontal') }}
    <div id="category_description_text">
        <?php echo Phalcon\Tag::hiddenField(['category_description']) ?>
    </div>
        <table class="table table-bordered table-condensed">
            <tr>
                <td><label for="category_title">Название:</label></td>
                <td>
                    {{ text_field("category_title", 'required' : '', 'class' : 'form-control') }}
                </td>
            </tr>
            <tr>
                <td><label for="category_description">Описание:</label></td>
                <td>
                    <div class="advanced-wrapper">
                        <div class="toolbar-container"><span class="ql-format-group">
                                <select title="Шрифт" class="ql-font">
                                    <option value="sans-serif" selected>Sans Serif</option>
                                    <option value="Georgia, serif">Serif</option>
                                    <option value="Monaco, &quot;Courier New&quot;, monospace">Monospace</option>
                                </select>
                                <select title="Размер шрифта" class="ql-size">
                                    <option value="10px">10x</option>
                                    <option value="13px" selected>13px</option>
                                    <option value="18px">18px</option>
                                    <option value="32px">32px</option>
                                </select></span><span class="ql-format-group"><span title="Bold" class="ql-format-button ql-bold"></span><span class="ql-format-separator"></span><span title="Italic" class="ql-format-button ql-italic"></span><span class="ql-format-separator"></span><span title="Underline" class="ql-format-button ql-underline"></span></span><span class="ql-format-group">
                                <select title="Цвет текста" class="ql-color">
                                    <option value="rgb(0, 0, 0)" selected></option>
                                    <option value="rgb(230, 0, 0)"></option>
                                    <option value="rgb(255, 153, 0)"></option>
                                    <option value="rgb(255, 255, 0)"></option>
                                    <option value="rgb(0, 138, 0)"></option>
                                    <option value="rgb(0, 102, 204)"></option>
                                    <option value="rgb(153, 51, 255)"></option>
                                    <option value="rgb(255, 255, 255)"></option>
                                    <option value="rgb(250, 204, 204)"></option>
                                    <option value="rgb(255, 235, 204)"></option>
                                    <option value="rgb(255, 255, 204)"></option>
                                    <option value="rgb(204, 232, 204)"></option>
                                    <option value="rgb(204, 224, 245)"></option>
                                    <option value="rgb(235, 214, 255)"></option>
                                    <option value="rgb(187, 187, 187)"></option>
                                    <option value="rgb(240, 102, 102)"></option>
                                    <option value="rgb(255, 194, 102)"></option>
                                    <option value="rgb(255, 255, 102)"></option>
                                    <option value="rgb(102, 185, 102)"></option>
                                    <option value="rgb(102, 163, 224)"></option>
                                    <option value="rgb(194, 133, 255)"></option>
                                    <option value="rgb(136, 136, 136)"></option>
                                    <option value="rgb(161, 0, 0)"></option>
                                    <option value="rgb(178, 107, 0)"></option>
                                    <option value="rgb(178, 178, 0)"></option>
                                    <option value="rgb(0, 97, 0)"></option>
                                    <option value="rgb(0, 71, 178)"></option>
                                    <option value="rgb(107, 36, 178)"></option>
                                    <option value="rgb(68, 68, 68)"></option>
                                    <option value="rgb(92, 0, 0)"></option>
                                    <option value="rgb(102, 61, 0)"></option>
                                    <option value="rgb(102, 102, 0)"></option>
                                    <option value="rgb(0, 55, 0)"></option>
                                    <option value="rgb(0, 41, 102)"></option>
                                    <option value="rgb(61, 20, 102)"></option>
                                </select><span class="ql-format-separator"></span>
                                <select title="Цвет фона текста" class="ql-background">
                                    <option value="rgb(0, 0, 0)"></option>
                                    <option value="rgb(230, 0, 0)"></option>
                                    <option value="rgb(255, 153, 0)"></option>
                                    <option value="rgb(255, 255, 0)"></option>
                                    <option value="rgb(0, 138, 0)"></option>
                                    <option value="rgb(0, 102, 204)"></option>
                                    <option value="rgb(153, 51, 255)"></option>
                                    <option value="rgb(255, 255, 255)" selected></option>
                                    <option value="rgb(250, 204, 204)"></option>
                                    <option value="rgb(255, 235, 204)"></option>
                                    <option value="rgb(255, 255, 204)"></option>
                                    <option value="rgb(204, 232, 204)"></option>
                                    <option value="rgb(204, 224, 245)"></option>
                                    <option value="rgb(235, 214, 255)"></option>
                                    <option value="rgb(187, 187, 187)"></option>
                                    <option value="rgb(240, 102, 102)"></option>
                                    <option value="rgb(255, 194, 102)"></option>
                                    <option value="rgb(255, 255, 102)"></option>
                                    <option value="rgb(102, 185, 102)"></option>
                                    <option value="rgb(102, 163, 224)"></option>
                                    <option value="rgb(194, 133, 255)"></option>
                                    <option value="rgb(136, 136, 136)"></option>
                                    <option value="rgb(161, 0, 0)"></option>
                                    <option value="rgb(178, 107, 0)"></option>
                                    <option value="rgb(178, 178, 0)"></option>
                                    <option value="rgb(0, 97, 0)"></option>
                                    <option value="rgb(0, 71, 178)"></option>
                                    <option value="rgb(107, 36, 178)"></option>
                                    <option value="rgb(68, 68, 68)"></option>
                                    <option value="rgb(92, 0, 0)"></option>
                                    <option value="rgb(102, 61, 0)"></option>
                                    <option value="rgb(102, 102, 0)"></option>
                                    <option value="rgb(0, 55, 0)"></option>
                                    <option value="rgb(0, 41, 102)"></option>
                                    <option value="rgb(61, 20, 102)"></option>
                                </select><span class="ql-format-separator"></span>
                                <select title="Text Alignment" class="ql-align">
                                    <option value="left" selected></option>
                                    <option value="center"></option>
                                    <option value="right"></option>
                                    <option value="justify"></option>
                                </select></span><span class="ql-format-group"><span title="Link" class="ql-format-button ql-link"></span><span class="ql-format-separator"></span><span title="Image" class="ql-format-button ql-image"></span><span class="ql-format-separator"></span><span title="Bullet" class="ql-format-button ql-bullet"></span></span><span class="ql-format-group"></span></div>
                        <div class="editor-container" some='new'>
                            <?php
                            $tidy = new tidy;
                            $config = array();

                            $tidy->parseString($category_description, $config, 'UTF8');
                            $tidy->cleanRepair();
                            echo $tidy 
                                    ?>
                        </div>
                    </div>
                </td>
            </tr>
            <tr>
                <td><label for="category_stopdatetime">Дата стопа:</label></td>
                <td>
                    <div class="input-append date" id="datetimepicker" data-date="<?= (isset($stop_datetime) ? $stop_datetime->format('d.m.Y H:00') : $date->format('d.m.Y H:00')) ?>" data-date-format="dd.mm.yyyy" date-language='ru'>
                        <input class="controls1" size="16" type="text" value="<?= (isset($stop_datetime) ? $stop_datetime->format('d.m.Y H:00') : $date->format('d.m.Y H:00')) ?>" name='category_stop_datetime' required="">
                        <span class="add-on"><i class="icon-calendar"></i></span>
                    </div> 
                </td>
            </tr>
            <?php if (isset($category_id)) { ?>
            <tr>
                <td><label for="update_datetime">В начало списка:</label></td>
                <td>
                    {{ check_field("update_datetime") }}
                </td>
            </tr>
            <?php } ?>
            <tr>
                <td><label for="category_hidden">Не показывать клиентам:</label></td>
                <td>
                    {{ check_field("category_hidden") }}
                </td>
            </tr>
            <tr>
                <td><label for="category_use_forum">Разрешить обсуждение:</label></td>
                <td>
                    {{ check_field("category_use_forum") }}
                </td>
            </tr>
            <tr>
                <td><label for="category_parent_id">Родительская категория:</label></td>
                <td>
                    {{ select("category_parent_id", parents, 'using' : ['id', 'title'], 'useEmpty' : true, 'emptyText' : '-', 'class' : 'form-control' ) }}
                </td>
            </tr>
            <tr>
                <td><label for="category_rules">Условия закупки:</label></td>
                <td>
                    <div class="advanced-wrapper1">
                        <div class="toolbar-container"><span class="ql-format-group">
                                <select title="Шрифт" class="ql-font">
                                    <option value="sans-serif" selected>Sans Serif</option>
                                    <option value="Georgia, serif">Serif</option>
                                    <option value="Monaco, &quot;Courier New&quot;, monospace">Monospace</option>
                                </select>
                                <select title="Размер шрифта" class="ql-size">
                                    <option value="10px">10x</option>
                                    <option value="13px" selected>13px</option>
                                    <option value="18px">18px</option>
                                    <option value="32px">32px</option>
                                </select></span><span class="ql-format-group"><span title="Bold" class="ql-format-button ql-bold"></span><span class="ql-format-separator"></span><span title="Italic" class="ql-format-button ql-italic"></span><span class="ql-format-separator"></span><span title="Underline" class="ql-format-button ql-underline"></span></span><span class="ql-format-group">
                                <select title="Цвет текста" class="ql-color">
                                    <option value="rgb(0, 0, 0)" selected></option>
                                    <option value="rgb(230, 0, 0)"></option>
                                    <option value="rgb(255, 153, 0)"></option>
                                    <option value="rgb(255, 255, 0)"></option>
                                    <option value="rgb(0, 138, 0)"></option>
                                    <option value="rgb(0, 102, 204)"></option>
                                    <option value="rgb(153, 51, 255)"></option>
                                    <option value="rgb(255, 255, 255)"></option>
                                    <option value="rgb(250, 204, 204)"></option>
                                    <option value="rgb(255, 235, 204)"></option>
                                    <option value="rgb(255, 255, 204)"></option>
                                    <option value="rgb(204, 232, 204)"></option>
                                    <option value="rgb(204, 224, 245)"></option>
                                    <option value="rgb(235, 214, 255)"></option>
                                    <option value="rgb(187, 187, 187)"></option>
                                    <option value="rgb(240, 102, 102)"></option>
                                    <option value="rgb(255, 194, 102)"></option>
                                    <option value="rgb(255, 255, 102)"></option>
                                    <option value="rgb(102, 185, 102)"></option>
                                    <option value="rgb(102, 163, 224)"></option>
                                    <option value="rgb(194, 133, 255)"></option>
                                    <option value="rgb(136, 136, 136)"></option>
                                    <option value="rgb(161, 0, 0)"></option>
                                    <option value="rgb(178, 107, 0)"></option>
                                    <option value="rgb(178, 178, 0)"></option>
                                    <option value="rgb(0, 97, 0)"></option>
                                    <option value="rgb(0, 71, 178)"></option>
                                    <option value="rgb(107, 36, 178)"></option>
                                    <option value="rgb(68, 68, 68)"></option>
                                    <option value="rgb(92, 0, 0)"></option>
                                    <option value="rgb(102, 61, 0)"></option>
                                    <option value="rgb(102, 102, 0)"></option>
                                    <option value="rgb(0, 55, 0)"></option>
                                    <option value="rgb(0, 41, 102)"></option>
                                    <option value="rgb(61, 20, 102)"></option>
                                </select><span class="ql-format-separator"></span>
                                <select title="Цвет фона текста" class="ql-background">
                                    <option value="rgb(0, 0, 0)"></option>
                                    <option value="rgb(230, 0, 0)"></option>
                                    <option value="rgb(255, 153, 0)"></option>
                                    <option value="rgb(255, 255, 0)"></option>
                                    <option value="rgb(0, 138, 0)"></option>
                                    <option value="rgb(0, 102, 204)"></option>
                                    <option value="rgb(153, 51, 255)"></option>
                                    <option value="rgb(255, 255, 255)" selected></option>
                                    <option value="rgb(250, 204, 204)"></option>
                                    <option value="rgb(255, 235, 204)"></option>
                                    <option value="rgb(255, 255, 204)"></option>
                                    <option value="rgb(204, 232, 204)"></option>
                                    <option value="rgb(204, 224, 245)"></option>
                                    <option value="rgb(235, 214, 255)"></option>
                                    <option value="rgb(187, 187, 187)"></option>
                                    <option value="rgb(240, 102, 102)"></option>
                                    <option value="rgb(255, 194, 102)"></option>
                                    <option value="rgb(255, 255, 102)"></option>
                                    <option value="rgb(102, 185, 102)"></option>
                                    <option value="rgb(102, 163, 224)"></option>
                                    <option value="rgb(194, 133, 255)"></option>
                                    <option value="rgb(136, 136, 136)"></option>
                                    <option value="rgb(161, 0, 0)"></option>
                                    <option value="rgb(178, 107, 0)"></option>
                                    <option value="rgb(178, 178, 0)"></option>
                                    <option value="rgb(0, 97, 0)"></option>
                                    <option value="rgb(0, 71, 178)"></option>
                                    <option value="rgb(107, 36, 178)"></option>
                                    <option value="rgb(68, 68, 68)"></option>
                                    <option value="rgb(92, 0, 0)"></option>
                                    <option value="rgb(102, 61, 0)"></option>
                                    <option value="rgb(102, 102, 0)"></option>
                                    <option value="rgb(0, 55, 0)"></option>
                                    <option value="rgb(0, 41, 102)"></option>
                                    <option value="rgb(61, 20, 102)"></option>
                                </select><span class="ql-format-separator"></span>
                                <select title="Text Alignment" class="ql-align">
                                    <option value="left" selected></option>
                                    <option value="center"></option>
                                    <option value="right"></option>
                                    <option value="justify"></option>
                                </select></span><span class="ql-format-group"><span title="Link" class="ql-format-button ql-link"></span><span class="ql-format-separator"></span><span title="Image" class="ql-format-button ql-image"></span><span class="ql-format-separator"></span><span title="Bullet" class="ql-format-button ql-bullet"></span></span><span class="ql-format-group"></span></div>
                        <div class="editor-container">
                            <?php
                            $tidy->parseString($category_rules, $config, 'UTF8');
                            $tidy->cleanRepair();
                            echo $tidy 
                                    ?>
                        </div>
                    </div>
                    <div id="category_rules_text">
                        <?php echo Phalcon\Tag::hiddenField(['category_rules']) ?>
                    </div>
                </td>
            </tr>
            <tr>
                <td><label for="category_photo">Изображение:</label></td>
                <td>
                    {{ file_field("category_photo", 'onchange' : 'removePhoto(); return false;') }}
                </td>
            </tr>
            <?php if (isset($category_id) && strlen($category_img)) { ?>
            <tr id='img_row'>
                <td class="cat_title">
                    {{ link_to('#', 'onclick' : 'removePhoto(); return false;', 'class' : "btn btn-warning", 'text' : 'Удалить изображение') }}
                </td>
                <td>
                    <div>
                        <img id='cat_img' class="cat_img" src="data:image/jpeg;charset=utf-8;base64,<?= $category_img ?>">
                    </div>
                    
                </td>
            </tr>
            <?php } ?>
        </table>
        
        <div class="control-group">
            <div class="controls">
        <?php if (isset($category_id)) { ?>
            {{ submit_button("Обновить", 'name' : 'update_category', 'class' : 'btn btn-lg btn-primary btn-block') }}
            
            {{ submit_button("В новую закупку", 'name' : 'clone_category', 'class' : 'btn btn-lg btn-primary btn-block') }}
            
            {{ hidden_field("category_id", 'value' : category_id) }}
            {{ hidden_field("category_img", 'value' : category_img) }}
        <?php } else { ?>
            {{ submit_button("Добавить", 'name' : 'add_category', 'class' : 'btn btn-lg btn-primary btn-block') }}
        <?php } ?>
            </div>
        </div>
        
    </form>
</div>
<script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/lodash.js/2.4.1/lodash.js"></script>
<script src="<?= $this->di->get('config')->application->baseUri ?>/js/quill.js"></script>
<script src="<?= $this->di->get('config')->application->baseUri ?>/js/quill_cat_desc.js"></script>
<script>
    <!--
    $(document).ready(function () {
        $("#datetimepicker").datetimepicker({
            format: 'dd.mm.yyyy hh:ii',
            autoclose: true,
            todayBtn: true,
            pickerPosition: "bottom-left",  
            language: 'ru',
            weekStart: 1
        });
    });
    
    function removePhoto() {
        $('#img_row').remove();
        $('#category_img').remove();
    }
    -->
</script>