<p><?php echo $this->getContent() ?></p>
<div>
    <div class="title">Найденный товары в закупке со 100sp.ru</div><br>
    <?php echo Phalcon\Tag::form(['/categories/fetch100sp', 'id' => 'fetch_100sp_form', 'class' => 'form-horizontal']) ?>
    <table class="table table-condensed table-bordered table-hover">
        <?php foreach ($items as $item) { ?>
        <tr>
            <td><?php echo Phalcon\Tag::textField(["item_names[]", 'value' => $item['name'], 'class' => 'form-control']) ?></td>
            <td><?php echo Phalcon\Tag::textField(["item_prices[]", 'value' => $item['price'], 'class' => 'form-control']) ?></td>
            <td><?php echo Phalcon\Tag::textarea(["item_descs[]", 'value' => $item['desc'], 'class' => 'form-control', 'rows' => 10]) ?></td>
            <td><img src="<?= $item['img_addr'] ?>" class="cat_img"></td>
            <td><pre><?= print_r($item['size'],1) ?></pre></td>
        </tr>
        <?php } ?>
    </table>
    <?php echo Phalcon\Tag::submitButton(["Загрузить", 'name' => 'fetch_100sp_form', 'class' => 'btn btn-lg btn-primary btn-block']) ?>
    </form>
</div>