<p><?php echo $this->getContent() ?></p>
<div>
    <div class="title">Список закупок товаров</div><br>
    
    <table class="table table-bordered table-condensed cat_table">
        <tr>
            <td class="cat_title">Название и фото</td>
            <td class="cat_desc">Описание</td>
            <td class="cat_products_count">Товаров в закупке</td>
            <td class="cat_products_count">Стоп</td>
            <td class="cat_products_count"></td>
            <td class="cat_products_count">Действия</td>
        </tr>
    <?php foreach ($categories as $category) { ?>
        <tr>
            <td class="cat_title">
                <div class="title"><?= $category->title ?></div>
                <?= $this->tag->linkTo(array(
                    '/categories/view/' . $category->id, 
                    'text' => 
                    (strlen($category->img) > 0 ? ('<img class="cat_img" src="data:image/jpeg;charset=utf-8;base64,' . $category->img . '">') : ('<img class="cat_img" src="/img/noimage.jpg">')))); ?>
            </td>
            <td class="cat_desc"><?= $category->desc ?></td>
            <?php if (Categories::hasChildCategories($category->id)) { ?>
            <td class="cat_products_count">-</td>
            <?php } else { ?>
            <td class="cat_products_count"><?= count(Product::find(array('conditions' => 'category_id = ?1', 'bind' => array( 1 => $category->id)))) ?></td>
            <?php } ?>
            <?php $stop_datetime = new DateTime($category->stop_datetime); ?>
            <?php $category_messages = AskAdminMessage::find(array(
                'conditions' => 'is_new = 1 AND category_id = ?1',
                'bind' => array(
                    1 => $category->id
                )
            )); ?>
            <td class="cat_products_count"><span class="<?= (!Categories::isStopped($category->id) ? '' : ' errorMessage ')  ?>"><?= $stop_datetime->format('d.m.Y H:i:s') ?></span></td>
            <td class="cat_products_count">
                <span class="glyphicon <?= $category->hidden ? 'glyphicon-eye-close' : '' ?>"></span>
                <?php if (count($category_messages)) { ?>
                <br>
                <?= $this->tag->linkTo(array(
                    '/categories/view_messages/' . $category->id, 
                    'text' => '<span title="Есть вопросы администратору" class="glyphicon glyphicon-comment"></span>'
                    )); ?>
                <?php } ?>
            </td>
            <td class="cat_products_count"><?= $this->tag->linkTo(array(
                '/categories/edit/' . $category->id, 
                'class' => 'btn btn-link',
                'text' => 'Изменить')) ?></td>
        </tr>
    <?php } ?>
    </table>
</div>
