<p><?php echo $this->getContent() ?></p>
<div>
    <div class="title">Список закупок товаров</div><br>
    
    <table class="table table-bordered table-condensed cat_table">
        <tr>
            <td class="cat_title">Название и фото</td>
            <td class="cat_desc">Описание</td>
            <td class="cat_products_count">Товаров в закупке</td>
            <td class="cat_products_count">Стоп</td>
            <td class="cat_products_count">Действия</td>
        </tr>
    <?php foreach ($categories as $category) { ?>
        <tr>
            <td class="cat_title">
                <div class="title"><?= $category->title ?></div>
                <?= $this->tag->linkTo(array(
                    '/categories/view/' . $category->id, 
                    'text' => 
                    (strlen($category->img) > 0 ? ('<img class="cat_img" src="data:image/jpeg;charset=utf-8;base64,' . $category->img . '">') : ('<img class="cat_img" src="/img/noimage.jpg">')))); ?>
            </td>
            <td class="cat_desc"><?= $category->desc ?></td>
            <td class="cat_products_count"><?= count(Product::find(array('conditions' => 'category_id = ?1', 'bind' => array( 1 => $category->id)))) ?></td>
            <?php $stop_datetime = new DateTime($category->stop_datetime); ?>
            <td class="cat_products_count"><span class="<?= (!Categories::isStopped($category->id) ? '' : ' errorMessage ')  ?>"><?= $stop_datetime->format('d.m.Y H:i:s') ?></span></td>
            <td class="cat_products_count"><?= $this->tag->linkTo(array(
                '/categories/edit/' . $category->id, 
                'class' => 'btn btn-link',
                'text' => 'Изменить')) ?></td>
        </tr>
    <?php } ?>
    </table>
</div>
