<p><?php echo $this->getContent() ?></p>
<div class="btn-toolbar" role="toolbar">
    <div class="btn-group">
        <?= $this->tag->linkTo(array(
            '/product/add/' . $category->id, 
            'text' => 'Добавить товар',
            'type' => 'button',
            'class' => 'btn btn-default'
            )); ?>
        <?php if ($category->parent_category_id) { ?>
        <?= $this->tag->linkTo(array(
            '/categories/view/' . $category->parent_category_id, 
            'text' => 'К родительской категории',
            'type' => 'button',
            'class' => 'btn btn-default'
            )); ?>
        <?php } ?>
        <?= $this->tag->linkTo(array(
            '/categories/index/', 
            'text' => 'Назад к списку закупок',
            'type' => 'button',
            'class' => 'btn btn-default'
            )); ?>
    </div>
</div>

<?php if (count($category_child_cats)) { ?>

<div>
    <br>
    <div class="">
        <div class="title">Условия закупки</div>
        <div class="alert alert-info"><?= $category->rules ?></div>
    </div>
    <br>
    <div class="title">Закупки в категории</div><br>
    <table class="table table-bordered table-condensed cat_table">
        <tr>
            <td class="cat_title">Название и фото</td>
            <td class="cat_desc">Описание</td>
            <td class="cat_products_count">Товаров в закупке</td>
            <td class="cat_products_count">Стоп</td>
            <td class="cat_products_count"></td>
            <td class="cat_products_count">Действия</td>
        </tr>
    <?php foreach ($category_child_cats as $category) { ?>
        <tr>
            <td class="cat_title">
                <div class="title"><?= $category->title ?></div>
                <?= $this->tag->linkTo(array(
                    '/categories/view/' . $category->id, 
                    'text' => 
                    (strlen($category->img) > 0 ? ('<img class="cat_img" src="data:image/jpeg;charset=utf-8;base64,' . $category->img . '">') : ('<img class="cat_img" src="/img/noimage.jpg">')))); ?>
            </td>
            <td class="cat_desc"><?= $category->desc ?></td>
            <?php if (Categories::hasChildCategories($category->id)) { ?>
            <td class="cat_products_count">-</td>
            <?php } else { ?>
            <td class="cat_products_count"><?= count(Product::find(array('conditions' => 'category_id = ?1', 'bind' => array( 1 => $category->id)))) ?></td>
            <?php } ?>
            <?php $stop_datetime = new DateTime($category->stop_datetime); ?>
            <td class="cat_products_count"><span class="<?= (!Categories::isStopped($category->id) ? '' : ' errorMessage ')  ?>"><?= $stop_datetime->format('d.m.Y H:i:s') ?></span></td>
            <td class="cat_products_count"><span class="glyphicon <?= $category->hidden ? 'glyphicon-eye-close' : '' ?>"></span></td>
            <td class="cat_products_count"><?= $this->tag->linkTo(array(
                '/categories/edit/' . $category->id, 
                'class' => 'btn btn-link',
                'text' => 'Изменить')) ?></td>
        </tr>
    <?php } ?>
    </table>
</div>

<?php } else { ?>

<div>
    <br>
    <?php if (strlen($category->rules) > 2) { ?>
    <div class="">
        <div class="title">Условия закупки &laquo;<?= $category->title ?>&raquo;</div>
        <div class="alert alert-info"><?= $category->rules ?></div>
    </div>
    <?php } ?>
    <?php echo Phalcon\Tag::form(['/categories/drop_products', 'id' => 'products_form', 'class' => 'form-horizontal']) ?>
    <div class="title">Товары в закупке</div><br>
    <div class="btn-toolbar" role="toolbar">
        <div class="btn-group">
        <?php echo Phalcon\Tag::submitButton(["Удалить выделенные", 'name' => 'drop_products', 'class' => 'btn btn-default']) ?>
        <?php echo Phalcon\Tag::hiddenField(['category_id']) ?>
        </div>
    </div>
    <br>
    <table class="table table-bordered table-condensed product_table">
    <?php foreach ($this->view->products as $product) { ?>
        <tr>
            <td style="width: 16px; vertical-align: middle; text-align: center" id="product_<?= $product->id ?>">
                <?= $this->tag->checkField(['uid[]', 'value' => $product->id]); ?>
            </td>
            <td style="width: 40px; vertical-align: middle; text-align: center" id="product_<?= $product->id ?>">
                <?= $this->tag->linkTo(array(
                    '/categories/view/' . $category->id . '#product_' . $product->id, 
                    'text' => '' . $product->id,
                    'title' => 'Номер товара'
                    )); ?>
            </td>
                <?php if (file_exists(__DIR__ . '/../../../public/img/products/img_' . $category->id . '_' .$product->id . '.jpg')) {
                    $img_data = 'data:image/jpeg;charset=utf-8;base64,' . base64_encode(file_get_contents(__DIR__ . '/../../../public/img/products/img_' . $category->id . '_' .$product->id . '.jpg'));
                } else {
                    $img_data = 'data:image/jpeg;charset=utf-8;base64,' . ProductImage::getProductImage($product->id);
                }
                ?>
			<td class="product_title">
                <div class="product_title"><?= $product->title ?></div>
                <?php echo $this->tag->linkTo(array(
                    '/product/view/' . $product->id, 
                    'text' => 
                    (strlen($img_data) > 0 ? ('<img class="cat_img" src="' . $img_data . '">') : ('<img class="cat_img" src="/img/noimage.jpg">'))
                    )); ?>
            </td>
            <td class="cat_desc"><?= $product->description ?></td>
            <td class="product_price price"><?= $product->price ?></td>
            <td><div>Размеры и заказы:</div>
                <?php
                $product_attributes = ProductAttribute::find(array(
                    'conditions' => 'product_id = ?1',
                    'bind' => array(
                        1 => $product->id
                    )
                ));
                ?>
                <table class="table product_attributes_table">
                    <?php foreach ($product_attributes as $attr) : ?>
                        <tr>
                            <td><?= $attr->attr ?></td>
                            <td>
                                <?php
                                if (!Categories::isStopped($product->category_id)) {
                                    echo $this->tag->linkTo(array(
                                        './#',
                                        'onclick' => 'return false;',
                                        'text' => 'Прием заказов',
                                        'class' => ''
                                        ));
                                } else {
                                    echo $this->tag->linkTo(array(
                                        './#',
                                        'onclick' => 'return false;',
                                        'text' => 'Закупка завершена',
                                        'class' => ''
                                        ));
                                }
                                ?>
                            </td>
                            <td>
                                <?php
                                $ordered_items = Order::find(array(
                                    'conditions' => 'product_id = ?1 AND product_attr_id = ?2',
                                    'bind' => array(
                                        1 => $product->id,
                                        2 => $attr->id
                                        
                                    ),
                                    'group' => 'user_id'
                                ));
                                ?>
                                <?php foreach ($ordered_items as $cur_item) { ?>
                                <div>
                                    <?= User::getLogin($cur_item->user_id) ?>
                                    <?php if (strlen($cur_item->info)) { ?>
                                    <a title="Посмотреть комментарий по заказу" href="#" data-reveal-id="myModal_<?= $attr->id ?>" onclick="return false;"><span class="glyphicon <?= strlen($cur_item->info) ? 'glyphicon-comment' : '' ?>"></span></a>
                                    <div id="myModal_<?= $attr->id ?>" class="reveal-modal">
                                        <h3>Комментарий</h3>
                                        <p><?= $cur_item->info ?></p>
                                        <a class="close-reveal-modal">&#215;</a>
                                   </div>
                                    <?php } ?>
                                </div>
                                <?php } ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </table>
            </td>
        </tr>
    <?php } ?>
    </table>
    </form>
</div>

<?php } ?>
<?php if ($category->use_forum > 0) { ?>
<?php echo Phalcon\Tag::form(['/categories/new_message', 'id' => 'forum_new_message_form', 'class' => 'form-horizontal']) ?>
<div class="forum_block" id="new_msg">
    <h3 class="help-block">Обсуждение закупки</h3>
    <div id="forum_new_msg">
        <table class="table">
            <tr>
                <td style='width: 70px;'><label for="forum_new_msg_text">Сообщение:</label></td>
                <td>
                    <?php echo Phalcon\Tag::textarea(["forum_new_msg_text", 'class' => 'form-control', 'rows' => 10]) ?>
                </td>
            </tr>
            <tr>
                <td></td>
                <td>
                    <?php echo Phalcon\Tag::submitButton(["Отправить", 'name' => 'forum_send_new_msg', 'class' => 'btn btn-default', 'onclick' => 'return check_forum_msg();']) ?>
                    <?php echo Phalcon\Tag::hiddenField(["category_id", 'value' => $category->id]) ?>
                </td>
            </tr>
        </table>
    </div>
    
    <table class="table table-condensed table-bordered forum_msgs_table">
        <?php foreach ($forum_msgs as $cur_msg) : ?>
        <tr class="forum_msg_row">
            <td style="width: 30px;">
                <?php echo $this->tag->linkTo(array(
                    './#',
                    'onclick' => 'removeForumMsg(this); return false;',
                    'text' => 'x',
                    'id' => $cur_msg->id
                    )); ?>
            </td>
            <td style="width: 40px;">
                 <?php echo $this->tag->linkTo(array(
                    '#' . $cur_msg->id,
                     'text' => '#' . $cur_msg->id,
                     'id' => $cur_msg->id
                    )); ?>
            </td>
            <td class="forum_msg_info">
                <span class="forum_info_user"><?= User::getLogin($cur_msg->user_id) ?></span>
                <span class="forum_info_date"><?= rus_date($cur_msg->item_datetime, true) ?></span>
            </td>
            <td class="forum_msg_text">
                <span class=""><?= $cur_msg->msg ?></span>
            </td>
        </tr>
        <?php endforeach; ?>
    </table>
</div>
</form>

<?php } ?>

<script>
    <!--
    function check_forum_msg() {
        if ($.trim($('#forum_new_msg_text').val()) !== '') {
            return true;
        } else {
            $('#forum_new_msg_text').select();
            $('#forum_new_msg_text').focus();
            return false;
        }
    }
    
    function removeForumMsg(el) {
        if (confirm('Удалить сообщение?')) {
            var data = {
                remove_forum_msg: 1,
                id: el.getAttribute('id')
            };
            $.post('/categories/remove_forum_msg', data, function (retData) {
                var retObj = JSON.parse(retData);
                if (retObj.hasError === true) {
                    alert(retObj.errorMsg);
                } else {
                    $(el).parents('tr.forum_msg_row').hide(400);
                }
            });
        }
    }
    -->
</script>
