<p><?php echo $this->getContent() ?></p>
<div class="btn-toolbar" role="toolbar">
    <div class="btn-group">
        <?= $this->tag->linkTo(array(
            '/product/add/' . $category->id, 
            'text' => 'Добавить товар',
            'type' => 'button',
            'class' => 'btn btn-default'
            )); ?>
        <?php if ($category->parent_category_id) { ?>
        <?= $this->tag->linkTo(array(
            '/categories/view/' . $category->parent_category_id, 
            'text' => 'К родительской категории',
            'type' => 'button',
            'class' => 'btn btn-default'
            )); ?>
        <?php } ?>
        <?= $this->tag->linkTo(array(
            '/categories/index/', 
            'text' => 'Назад к списку закупок',
            'type' => 'button',
            'class' => 'btn btn-default'
            )); ?>
    </div>
</div>

<?php if (count($category_child_cats)) { ?>

<div>
    <br>
    <div class="title">Закупки в категории</div><br>
    <table class="table table-bordered table-condensed cat_table">
        <tr>
            <td class="cat_title">Название и фото</td>
            <td class="cat_desc">Описание</td>
            <td class="cat_products_count">Товаров в закупке</td>
            <td class="cat_products_count">Стоп</td>
            <td class="cat_products_count">Действия</td>
        </tr>
    <?php foreach ($category_child_cats as $category) { ?>
        <tr>
            <td class="cat_title">
                <div class="title"><?= $category->title ?></div>
                <?= $this->tag->linkTo(array(
                    '/categories/view/' . $category->id, 
                    'text' => 
                    (strlen($category->img) > 0 ? ('<img class="cat_img" src="data:image/jpeg;charset=utf-8;base64,' . $category->img . '">') : ('<img class="cat_img" src="/img/noimage.jpg">')))); ?>
            </td>
            <td class="cat_desc"><?= $category->desc ?></td>
            <td class="cat_products_count"><?= count(Product::find(array('conditions' => 'category_id = ?1', 'bind' => array( 1 => $category->id)))) ?></td>
            <?php $stop_datetime = new DateTime($category->stop_datetime); ?>
            <td class="cat_products_count"><span class="<?= (!Categories::isStopped($category->id) ? '' : ' errorMessage ')  ?>"><?= $stop_datetime->format('d.m.Y H:i:s') ?></span></td>
            <td class="cat_products_count"><?= $this->tag->linkTo(array(
                '/categories/edit/' . $category->id, 
                'class' => 'btn btn-link',
                'text' => 'Изменить')) ?></td>
        </tr>
    <?php } ?>
    </table>
</div>

<?php } else { ?>

<div>
    <br>
    <div class="">
        <div class="title">Условия закупки &laquo;<?= $category->title ?>&raquo;</div>
        <div class="alert alert-info"><?= $category->rules ?></div>
    </div>
    
    <div class="title">Товары в закупке</div><br>
    <table class="table table-bordered table-condensed product_table">
    <?php foreach ($this->view->products as $product) { ?>
        <tr>
            <td class="product_title">
                <div class="title"><?= $product->title ?></div>
                <?php echo $this->tag->linkTo(array(
                    '/product/view/' . $product->id, 
                    'text' => 
                    (strlen(ProductImage::getProductImage($product->id)) > 0 ? ('<img class="cat_img" src="data:image/jpeg;charset=utf-8;base64,' . ProductImage::getProductImage($product->id) . '">') : ('<img class="cat_img" src="/img/noimage.jpg">'))
                    )); ?>
            </td>
            <td class="cat_desc"><?= $product->description ?></td>
            <td class="product_price price"><?= $product->price ?></td>
        </tr>
    <?php } ?>
    </table>
</div>

<?php } ?>
