<p><?php echo $this->getContent() ?></p>
<div>
    <div class="title">Список заказов</div><br>
    <table class="table table-bordered table-condensed">
        <thead>
            <tr>
                <th>Закупка</th>
                <th>Товары</th>
            </tr>
        </thead>
        <tbody>
            <?php $order_statuses = OrderStatus::find(array('order' => 'status_title')); ?>
            <?php foreach ($categories as $cur_category => $category_orders) : ?>
                <tr class="category_row">
                    <td class="cat_title">
                        <div class="title btn-link orders_table_switcher"><?= Categories::getTitle($cur_category) ?></div>
                        <?php $category = Categories::findFirst($cur_category); ?>
                        <?= (strlen($category->img) > 0 ? ('<img class="cat_img" src="data:image/jpeg;charset=utf-8;base64,' . $category->img . '">') : ('<img class="cat_img" src="/img/noimage.jpg">')) ?>
                        <div>Всего товаров: <?= count($categories[$cur_category]['orders']) ?></div>
                        <div class="price">На сумму: <?= $categories[$cur_category]['order_summa'] ?></div>
                        <div>{{ link_to('/product/send_messages/' ~ cur_category, 'text': 'Отправить сообщение по закупке') }}</div>
                        <div>Скрыть картинки {{ check_field('img_hider[]', 'onclick' : 'toggleImages(this)') }}</div>
                    </td>
                    <td class="order_items">
                        <table class="table table-bordered table-condensed product_table">
                            <thead>
                                <tr class="warning">
                                    <th>Заказ</th>
                                    <th>Товар</th>
                                    <th class="prod_img"></th>
                                    <th>Размер</th>
                                    <th>Кол</th>
                                    <th>Сумма</th>
                                    <th>Пользователь</th>
                                    <th>Дата заказа</th>
                                    <th></th>
                                    <th style='width: 100px;'></th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach ($category_orders['orders'] as $cur_order) { ?>
                                    <?php $order = SpOrder::findFirst($cur_order) ?>
                                    <tr class="<?= $order->is_approved ? 'text-success' : 'text-muted' ?>">
                                        <td><?php
                                            echo $this->tag->linkTo(array(
                                                '/order/view/' . $order->id,
                                                'class' => 'btn',
                                                'text' => $order->id));
                                            ?></td>
                                        <td><?= Product::getProductTitle($order->product_id) ?></td>
                                        <td class="product_title prod_img">
                                            <?php if (file_exists(__DIR__ . '/../../../public/img/products/img_sm_' . $order->product->category_id . '_' .$order->product_id . '.jpg')) {
                                                echo '<img class="cat_img" src="', 
                                                        '/img/products/img_sm_' . $order->product->category_id . '_' .$order->product_id . '.jpg'
                                                        , '">';
                                            } else {
                                                echo '-';
                                            }
                                            ?>
                                        </td>
                                        <td><?= ProductAttribute::getAttributeTitle($order->product_attr_id) ?></td>
                                        <td><?= $order->product_count ?></td>
                                        <td><?= number_format($order->order_summa, 0, ',', '') ?></td>
                                        <td><?= User::getLogin($order->user_id) ?></td>
                                        <td><?= rus_date($order->order_datetime, true) ?></td>
                                        <?php $messages = Categories::getOrderMessages($order->product_id); ?>
                                        <td class="product_price">
                                            <?php if (strlen($order->info)) { ?>
                                                <a title="Посмотреть комментарий по заказу" href="#" data-reveal-id="myModal_<?= $order->id ?>" onclick="return false;"><span class="glyphicon <?= strlen($order->info) ? 'glyphicon-comment' : '' ?>"></span></a>
                                                <div id="myModal_<?= $order->id ?>" class="reveal-modal">
                                                    <h3>Комментарий</h3>
                                                    <p><?= $order->info ?></p>
                                                    <a class="close-reveal-modal">&#215;</a>
                                                </div>
                                            <?php } ?>
                                            <span style="margin-right: 0.5em;" class="glyphicon <?= (count($messages) > 0 ? 'glyphicon-envelope' : '') ?>"></span>
                                        </td>
                                        <td><?= User::getLocation($order->user_id) ?></td>
                                    </tr>
                                <?php } ?>
                            </tbody>
                        </table>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>

<script>
    <!--
    $(document).ready(function() {
        $('.orders_table_switcher').click(function() {
            $(this).parents('.category_row').find('.order_items table').toggle();
        });
    });
    
    function toggleImages(el) {
        $(el).parents('.category_row').find('.prod_img').toggle();
    }
    
    function ordersChangeStatus(el) {
        var data = {
            update_orders: 1,
            category_id: $(el).parents('.changeStatusDialog').attr('category_id'),
            order_status_id: $(el).parents('.changeStatusDialog').find('.order_status_id option:selected').val()
        };
        console.info(data);
        $.post('/categories/update_orders', data, function (retData) {
            var retObj = JSON.parse(retData);
            if (typeof retObj === 'object') {
                if (retObj.hasError === true) {
                    $(el).parents('.changeStatusDialog').find('.err_block').addClass('alert alert-danger').html(retObj.errorMsg);
                } else {
                    location.reload();
                }
            }
        });
        return false;
    }
-->
</script>
