<h4 class="well well-sm">{{ title }}</h4>
<p><?php echo $this->getContent() ?></p>

<div class="carousel">
    <div class="page-header">
        <h4>Сообщения</h4>
    </div>

    <table class="table table-bordered table-condensed">
        <?php foreach ($messages as $msg) { ?>
        <tr>
            <td style='width: 10px; display: none;'><?= Phalcon\Tag::checkField(["message_ids[]", 'value' => $msg->id]) ?></td>
            <td>
                <a href='#' class="msg_subj" onclick="toggle_msg_body(this); return false;"><?= Categories::getTitle($msg->category_id) ?></a>
                <div class='msg_body'><pre><?= $msg->msg ?></pre></div>
            </td>
            <td style='width: 150px;'><?= rus_date($msg->item_datetime, true) ?></td>
            <td style='width: 150px; <?= $msg->client_id < 1 ? 'font-weight: bold' : '' ?>'><?= User::getLogin($msg->client_id) ?></td>
            <td style='width: 80px;'>
                    <?=
                    $this->tag->linkTo(array(
                        '/profile/reply_message/' . $msg->id,
                        'text' => 'Ответить',
                        'type' => 'button',
                        'class' => 'btn btn-link btn-sm'
                    ));
                    ?>
            </td>
        </tr>
        <?php } ?>
    </table>
</div>

<script>
    <!--
    function toggle_msg_body(el) {
        var cell = $(el).parent('td');
        $(cell).find('.msg_body').toggle();
    }
    -->
</script>