<div class="col-md-8 col-md-offset-2">
    
    <div class="page-header">
        <h4>Оставить комментарий к заказу # <?= $order->id ?></h4>
    </div>
    
    <p><?php echo $this->getContent() ?></p>
    
    <?php echo Phalcon\Tag::form(['/product/save_comment', 'id' => 'msg_form', 'class' => 'form-horizontal']) ?>
    
        <div class="control-group">
            <label class="control-label" for="msg">Сообщение</label>
            <div class="controls">
                <?php echo Phalcon\Tag::textarea(["comment", 'class' => 'form-control']) ?>
            </div>
        </div>

    <br>
        <div class="control-group">
            <div class="controls">
                <?php echo Phalcon\Tag::submitButton(["Отправить", 'class' => 'btn btn-lg btn-primary btn-block']) ?>
            </div>
        </div>

        <div class="control-group">
            <div class="controls">
        <?php echo Phalcon\Tag::hiddenField(["order_id", 'value' => $order->id]) ?>
            </div>
        </div>

    </form>
</div>
