<p><?php echo $this->getContent() ?></p>
<div>
    <table class="table table-bordered table-condensed product_table">
    <?php foreach ($this->view->products as $product) { ?>
        <tr>
            <td class="product_title">
                <?= $product->title ?><br>
                <?php echo $this->tag->linkTo(array(
                    '/product/view/' . $product->id, 
                    'text' => '<img class="product_img" src="/img/construction.gif">')); ?>
            </td>
            <td class="cat_desc"><?= $product->description ?></td>
            <td><?= $product->price ?></td>
        </tr>
    <?php } ?>
    </table>
</div>