<div class="col-md-9 col-md-offset-2">
    
    <div class="page-header">
        <h4>Список пользователей</h4>
    </div>
    
    <p><?php echo $this->getContent() ?></p>
    
    <table class="table table-bordered table-condensed table-hover table-striped">
        <tr>
            <th>Логин</th>
            <th>Имя</th>
            <th>Телефон</th>
            <th>Город</th>
            <th>Активен</th>
        </tr>
        <?php foreach ($users as $user) { ?>
        <tr>
            <td><?= $user->login ?></td>
            <td><?= $user->full_name ?></td>
            <td><?= $user->phone ?></td>
            <td><?= $user->location ?></td>
            <td><?= $user->is_alive ? 'Да' : 'Нет' ?></td>
        </tr>
        <?php } ?>
    </table>
    
    <div class="help-block">
        <div>Всего пользователей: <?= count($users) ?></div>
        <div>Активных: <?= count($active_users) ?></div>
        <div>Не активных: <?= count($inactive_users) ?></div>
    </div>
</div>