<div class="col-md-12">
    
    <div class="page-header">
        <h4>Список пользователей</h4>
    </div>
    
    <p><?php echo $this->getContent() ?></p>
    
    <table class="table table-bordered table-condensed table-hover table-striped">
        <tr>
            <th>Логин</th>
            <th>Имя</th>
            <th>Телефон</th>
            <th>Город</th>
            <th>Email</th>
        </tr>
        {% for user in users %}
        <tr>
            <td>{{ user.login }}</td>
            <td>{{ user.full_name }}</td>
            <td><a target='_blank' href='tel:{{ user.phone|escape_attr }}'>{{ user.phone }}</a></td>
            <td>{{ user.location }}</td>
            <td><a href='mailto:{{ user.email|escape_attr }}'>{{ user.email }}</a></td>
        </tr>
        {% endfor %}
    </table>
    
    <div class="help-block">
        <div>Всего пользователей: <?= count($users) ?></div>
    </div>
</div>
