<div class="col-md-4 offset4">
    
    <div class="page-header">
        <h4>Смена пароля администратора</h4>
    </div>
    <p>{{ content() }}</p>

    {{ form('/profile/set_pass', 'id' : 'reg_form', 'class' : 'form-horizontal') }}

    <div class="control-group">
        <label class="control-label" for="login">Логин</label>
        <div class="controls">
            {{ text_field("login", 'type' : 'text', 'required' : '', 'class' : 'form-control') }}
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="password">Пароль</label>
        <div class="controls">
            {{ text_field("password", 'class' : 'form-control') }}
        </div>
    </div>
    <br>

    <div class="control-group">
        <div class="controls">
            {{ submit_button("Вперед", 'class' : 'btn btn-lg btn-primary btn-block') }}
        </div>
    </div>

</form>
</div>