<div class="col-md-12">
    
    <p>{{ content() }}</p>
    
    {% if (messages|length > 0) %}
    {{ form('/profile/update_messages', 'id' : 'messages_form', 'class' : 'form-horizontal') }}
    
    <div class="btn-toolbar" role="toolbar">
        <div class="btn-group">
            {{ link_to('/profile/', 'text' : 'Назад к профилю', 'type' : 'button', 'class' : 'btn btn-default') }}
        </div>
    </div>
    <br>
    
    <div class="carousel">
        <div class="page-header">
            <h4>Входящие сообщения</h4>
        </div>
        <div class="btn-toolbar form-group" role="toolbar">
            <div class="btn-group">
                {{ submit_button("Показать все", 'name' : 'all_messages', 'class' : 'btn btn-default') }}
                {{ submit_button("Показать не прочтенные", 'name' : 'unread_messages', 'class' : 'btn btn-default') }}
                {{ submit_button("Удалить", 'name' : 'remove_messages', 'class' : 'btn btn-default') }}
                {{ submit_button("Пометить прочтенными", 'name' : 'mark_messages_read', 'class' : 'btn btn-default') }}
            </div>
        </div>
        <table class="table table-bordered table-condensed">
            {% for msg in messages %}
            <tr class='{{ msg.is_new ? 'new_message' : ''}}'>
                <td style='width: 10px;'>{{ check_field("message_ids[]", 'value' : msg.id) }}</td>
                <td>
                    <a href='#' class="msg_subj" onclick="toggle_msg_body(this); return false;">{{ msg.msg_subject }}</a>
                    <div class='msg_body'><pre>{{ msg.msg }}</pre></div>
                </td>
                <td style='width: 150px;'>{{ msg.item_datetime|rus_date(1) }}</td>
                <td style='width: 150px; {{ msg.from_user_id < 1 ? 'font-weight: bold' : '' }}'>{{ msg.user.login }}</td>
                <td style='width: 80px;'>
                    {{ link_to('/profile/reply_message/' ~ msg.id, 'text' : 'Ответить', 'type' : 'button', 'class' : 'btn btn-link btn-sm') }}
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>
    {% else %}
    <div class="carousel">
        <div class="page-header">
            <h4>Нет входящих сообщений</h4>
        </div>
    </div>
    {% endif %}
    </form>
    
    {{ form('/profile/update_messages', 'id' : 'outgoing_messages_form', 'class' : 'form-horizontal') }}
    
    {% if (outgoing_messages|length > 0) %}
    <div class="carousel">
        <div class="page-header">
            <h4>Исходящие сообщения</h4>
        </div>
        <div class="btn-toolbar form-group" role="toolbar">
            <div class="btn-group">
                {{ submit_button("Удалить", 'name' : 'remove_outgoing_messages', 'class' : 'btn btn-default') }}
            </div>
        </div>
        <table class="table table-bordered table-condensed">
            {% for msg in outgoing_messages %}
            <tr class='{{ msg.is_new ? 'new_message' : ''}}'>
                <td style='width: 10px;'>{{ check_field("outgoing_message_ids[]", 'value' : msg.id) }}</td>
                <td>
                    <a href='#' class="msg_subj" onclick="toggle_msg_body(this); return false;">{{ msg.msg_subject }}</a>
                    <div class='msg_body'><pre>{{ msg.msg }}</pre></div>
                </td>
                <td style='width: 150px;'>{{ msg.receiver.login }}</td>
                <td style='width: 150px;'>{{ msg.item_datetime|rus_date(1) }}</td>
            </tr>
            {% endfor %}
        </table>
    </div>
    {% else %}
    <div class="carousel">
        <div class="page-header">
            <h4>Нет исходящих сообщений</h4>
        </div>
    </div>
    {% endif %}
    
    </form>
    
</div>

<script>
    <!--
    function toggle_msg_body(el) {
        var cell = $(el).parent('td');
        $(cell).find('.msg_body').toggle();
    }
    -->
</script>