<div class="col-md-12">
    
    <p>{{ content() }}</p>
    
    {{ form('/profile/reply_message', 'id' : 'message_form', 'class' : 'form-horizontal') }}
    
    <div class="btn-toolbar" role="toolbar">
        <div class="btn-group">
            {{ link_to('/profile/messages', 'text' : 'Назад к сообщениям', 'type' : 'button', 'class' : 'btn btn-default') }}
        </div>
    </div>
    
    <div class="carousel">
        <div class="page-header">
            <h4>Ответ на сообщение</h4>
        </div>
        
        <table class="table table-bordered table-condensed">
            <tr>
                <td style="width: 100px">Тема</td>
                <td>{{ text_field("msg_subject", 'class' : 'form-control') }}</td>
            </tr>
            <tr>
                <td>Ответ</td>
                <td>{{ text_area("msg_text", 'class' : 'form-control', 'rows' : 10, 'autofocus' : '') }}</td>
            </tr>
        </table>
        <div class="form-actions">
            {{ submit_button("Отправить", 'name' : 'send_reply', 'class' : 'btn btn-default') }}
            <td>{{ hidden_field("msg_id") }}</td>
        </div>
    </div>
    
    </form>
    
</div>