<div class="col-md-8 col-md-offset-2">

    <div class="page-header">
        <h4>Оставить сообщение по заказам в закупке &laquo;<?= $category->title ?>&raquo;</h4>
    </div>

    <p><?php echo $this->getContent() ?></p>

    <?php echo Phalcon\Tag::form(['/categories/save_msg', 'id' => 'msg_form', 'class' => 'form-horizontal']) ?>

    <div class="control-group">
        <label class="control-label" for="summa">Сумма</label>
        <div class="controls">
            <?php echo Phalcon\Tag::textField(["summa", 'class' => 'numeric form-control']) ?>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="payment_type">Тип оплаты</label>
        <div class="controls">
            <?php
            echo Phalcon\Tag::select(["payment_type",
                ['Картой', 'Наличными'],
                //'using' => array('id', 'title'), 
                'class' => 'form-control'])
            ?>
        </div>
    </div>
    
    <div class="control-group">
        <label class="control-label" for="payment_date">Дата платежа</label>
        <div class="controls">
            <div class="input-append date" id="datetimepicker" data-date="<?= strtotime('d.m.Y') ?>" data-date-format="dd.mm.yyyy" date-language='ru'>
                <input class="controls1" size="16" type="text" value="<?= strtotime('d.m.Y') ?>" name='payment_date'>
                <span class="add-on"><i class="icon-calendar"></i></span>
            </div> 
        </div>
    </div>
    
    <div class="control-group">
        <label class="control-label" for="msg">Доп. информация (номер карты и т.п.)</label>
        <div class="controls">
            <?php echo Phalcon\Tag::textarea(["msg", 'required' => '', 'rows' => 5, 'class' => 'form-control']) ?>
        </div>
    </div>

    <br>
    <div class="control-group">
        <div class="controls">
<?php echo Phalcon\Tag::submitButton(["Отправить", 'class' => 'btn btn-lg btn-primary btn-block']) ?>
        </div>
    </div>

    <div class="control-group">
        <div class="controls">
<?php echo Phalcon\Tag::hiddenField(["category_id", 'value' => $category->id]) ?>
        </div>
    </div>

</form>
</div>

<script>
    <!--
    $(document).ready(function() {
        $('.numeric').numeric();
        $("#datetimepicker").datetimepicker({
            format: 'dd.mm.yyyy',
            autoclose: true,
            pickTime: true,
            todayBtn: true,
            pickerPosition: "bottom-left",  
            language: 'ru',
            weekStart: 1
        });
    });
-->
</script>