<div class="col-md-8 col-md-offset-2">
    
    <div class="page-header">
        <h4>Оставить сообщение по заказам в закупке &laquo;<?= $category->title ?>&raquo;</h4>
    </div>
    
    <p><?php echo $this->getContent() ?></p>
    
    <?php echo Phalcon\Tag::form(['/categories/save_msg', 'id' => 'msg_form', 'class' => 'form-horizontal']) ?>
    
        <div class="control-group">
            <label class="control-label" for="msg">Сообщение</label>
            <div class="controls">
                <?php echo Phalcon\Tag::textarea(["msg", 'required' => '', 'class' => 'form-control']) ?>
            </div>
        </div>

    <br>
        <div class="control-group">
            <div class="controls">
                <?php echo Phalcon\Tag::submitButton(["Отправить", 'class' => 'btn btn-lg btn-primary btn-block']) ?>
            </div>
        </div>

        <div class="control-group">
            <div class="controls">
        <?php echo Phalcon\Tag::hiddenField(["category_id", 'value' => $category->id]) ?>
            </div>
        </div>

    </form>
</div>