<p><?php echo $this->getContent() ?></p>
<div class="btn-toolbar" role="toolbar">
    <div class="btn-group">
        <?= $this->tag->linkTo(array(
            '/categories/index/', 
            'text' => 'Назад к списку закупок',
            'type' => 'button',
            'class' => 'btn btn-default'
            )); ?>
        <?php if ($category->parent_category_id) { ?>
        <?= $this->tag->linkTo(array(
            '/categories/view/' . $category->parent_category_id, 
            'text' => 'К родительской категории',
            'type' => 'button',
            'class' => 'btn btn-default'
            )); ?>
        <?php } ?>
    </div>
</div>

<?php if (count($category_child_cats)) { ?>

<div>
    <br>
    <div class="">
        <div class="title">Условия закупки</div>
        <div class="alert alert-info"><?= $category->rules ?></div>
    </div>
    <br>
    <div class="title">Закупки в категории &laquo;<?= $category->title ?>&raquo;</div><br>
    <table class="table table-bordered table-condensed cat_table">
        <tr>
            <td class="cat_title">Название и фото</td>
            <td class="cat_desc">Описание</td>
            <td class="cat_products_count">Товаров в закупке</td>
            <td class="cat_products_count">Стоп</td>
        </tr>
    <?php foreach ($category_child_cats as $cur_category) { ?>
        <tr>
            <td class="cat_title">
                <div class="title"><?= $cur_category->title ?></div>
                <?= $this->tag->linkTo(array(
                    '/categories/view/' . $cur_category->id, 
                    'text' => 
                    (strlen($cur_category->img) > 0 ? ('<img class="cat_img" src="data:image/jpeg;charset=utf-8;base64,' . $cur_category->img . '">') : ('<img class="cat_img" src="/img/noimage.jpg">')))); ?>
            </td>
            <td class="cat_desc"><?= $cur_category->desc ?></td>
            <td class="cat_products_count"><?= count(Product::find(array('conditions' => 'category_id = ?1', 'bind' => array( 1 => $cur_category->id)))) ?></td>
            <?php $stop_datetime = new DateTime($cur_category->stop_datetime); ?>
            <td class="cat_products_count"><span class="<?= (!Categories::isStopped($cur_category->id) ? '' : ' errorMessage ')  ?>"><?= $stop_datetime->format('d.m.Y H:i:s') ?></span></td>
        </tr>
    <?php } ?>
    </table>
</div>

<?php } else { ?>

<div>
    <br>
    <div class="">
        <div class="title">Условия закупки</div>
        <div class="alert alert-info"><?= $category->rules ?></div>
    </div>
    
    <div class="title">Товары в закупке &laquo;<?= $category->title ?>&raquo;</div><br>
    <table class="table table-bordered table-condensed product_table">
    <?php foreach ($this->view->products as $product) { ?>
        <tr>
            <td style="width: 40px; vertical-align: middle; text-align: center" id="product_<?= $product->id ?>">
                <?= $this->tag->linkTo(array(
                    '/categories/view/' . $category->id . '#product_' . $product->id, 
                    'text' => '' . $product->id,
                    'title' => 'Номер товара'
                    )); ?>
            </td>
            <td class="product_title">
                <?php if (file_exists(__DIR__ . '/../../../public/img/products/img_' . $category->id . '_' .$product->id . '.jpg')) {
                    $img_data = '/img/products/img_' . $category->id . '_' .$product->id . '.jpg'; 
                } else {
                    $img_data = 'data:image/jpeg;charset=utf-8;base64,' . ProductImage::getProductImage($product->id);
                }
                if (file_exists(__DIR__ . '/../../../public/img/products/img_sm_' . $category->id . '_' .$product->id . '.jpg')) {
                    $small_img_data = '/img/products/img_sm_' . $category->id . '_' .$product->id . '.jpg'; 
                } else {
                    $small_img_data = 'data:image/jpeg;charset=utf-8;base64,' . ProductImage::getProductImage($product->id);
                }
                ?>
                <div class="title"><?= $product->title ?></div>
				<?php echo (strlen($img_data) ?
					('<img class="cat_img prod_cat_img" src="' . $small_img_data . '" data-zoom-image="' . $img_data . '">')
					:
				   	('<img class="cat_img" src="/img/noimage.jpg">'))
                    ; ?>
            </td>
            <td class="cat_desc"><?= $product->description ?></td>
            <td class="product_price price"><?= $product->price ?></td>
            <td><div>Размеры и заказы:</div>
                <?php
                $product_attributes = ProductAttribute::find(array(
                    'conditions' => 'product_id = ?1',
                    'bind' => array(
                        1 => $product->id
                    )
                ));
                ?>
                <table class="table product_attributes_table">
                    <?php foreach ($product_attributes as $attr) : ?>
                        <tr>
                            <td><?= $attr->attr ?></td>
                            <td>
                                <?php
                                if (!Categories::isStopped($product->category_id)) {
                                    echo $this->tag->linkTo(array(
                                        '/product/order/' . $product->id .'/' . $attr->id,
                                        'text' => 'Заказать',
                                        'class' => ''
                                        ));
                                } else {
                                    echo $this->tag->linkTo(array(
                                        './#',
                                        'onclick' => 'return false;',
                                        'text' => 'Закупка завершена',
                                        'class' => ''
                                        ));
                                }
                                ?>
                            </td>
                            <td>
                                <?php
                                $ordered_users = Order::find(array(
                                    'conditions' => 'product_id = ?1 AND product_attr_id = ?2',
                                    'bind' => array(
                                        1 => $product->id,
                                        2 => $attr->id
                                        
                                    ),
                                    'group' => 'user_id'
                                ));
                                ?>
                                <?php foreach ($ordered_users as $cur_user) { ?>
                                <div><?= User::getLogin($cur_user->user_id) ?></div>
                                <?php } ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </table>
            </td>
        </tr>
    <?php } ?>
    </table>
</div>

<?php } ?>

<?php if ($category->use_forum > 0) { ?>
<?php echo Phalcon\Tag::form(['/categories/new_message', 'id' => 'forum_new_message_form', 'class' => 'form-horizontal']) ?>
<div class="forum_block" id="new_msg">
    <h3 class="help-block">Обсуждение закупки</h3>
    <div id="forum_new_msg">
        <table class="table">
            <tr>
                <td style='width: 70px;'><label for="forum_new_msg_text">Сообщение:</label></td>
                <td>
                    <?php echo Phalcon\Tag::textarea(["forum_new_msg_text", 'class' => 'form-control']) ?>
                </td>
            </tr>
            <tr>
                <td>Проверочные символы</td>
                <td>
                    <?= Recaptcha::get('6LdFpfQSAAAAACrEsxtX55STBL26Ax8s2Z4N9YFd'); ?>
                </td>
            </tr>
            <tr>
                <td></td>
                <td>
                    <?php echo Phalcon\Tag::submitButton(["Отправить", 'name' => 'forum_send_new_msg', 'class' => 'btn btn-default', 'onclick' => 'return check_forum_msg();']) ?>
                    <?php echo Phalcon\Tag::hiddenField(["category_id", 'value' => $category->id]) ?>
                </td>
            </tr>
        </table>
    </div>
    
    <table class="table table-condensed table-bordered forum_msgs_table">
        <?php foreach ($forum_msgs as $cur_msg) : ?>
        <tr>
            <td style="width: 40px;">
                 <?php echo $this->tag->linkTo(array(
                    '#' . $cur_msg->id,
                     'text' => '#' . $cur_msg->id,
                     'id' => $cur_msg->id
                    )); ?>
            </td>
            <td class="forum_msg_info">
                <span class="forum_info_user"><?= User::getLogin($cur_msg->user_id) ?></span>
                <span class="forum_info_date"><?= rus_date($cur_msg->item_datetime, true) ?></span>
            </td>
            <td class="forum_msg_text">
                <span class=""><?= $cur_msg->msg ?></span>
            </td>
        </tr>
        <?php endforeach; ?>
    </table>
</div>
</form>

<?php } ?>

<script>
    <!--
    function check_forum_msg() {
        if ($.trim($('#forum_new_msg_text').val()) !== '') {
            return true;
        } else {
            $('#forum_new_msg_text').select();
            $('#forum_new_msg_text').focus();
            return false;
        }
    }

	$('.prod_cat_img').elevateZoom({
		lensBorder: 0,
			zoomWindowWidth: 250,
			zoomWindowHeight: 200,
	}); 

	Zoomerang
		.config({
			maxHeight: 1024,
			maxWidth: 800,
			bgColor: '#000',
			bgOpacity: .85
		}).listen('.prod_cat_img');
    -->
</script>
