<p>{{ get_content() }}</p>
<div class="btn-toolbar" role="toolbar">
    <div class="btn-group">
		{{ link_to('/categories/index/', 'text' : 'Назад к списку закупок', 'type' : 'button', 'class' : 'btn btn-default') }}
		{% if category.parent_category_id > 0 %}
			{{ link_to('/categories/view/' ~ category.parent_category_id, 'text' : 'К родительской категории', 'type' : 'button', 'class' : 'btn btn-default') }}
		{% endif %}
    </div>
	{% if category.parent_category_id < 1 %}
        <div style="text-align: right; float: right;">
			{{ link_to('./#' ~ category.id, 'text' : 'Вопрос администратору', 'onclick' : 'askAdmin(); return false;', 'class' : 'btn btn-link alert alert-warning') }}
        </div>
	{% endif %}
</div>

<div id="ask_admin_div" class="form-group form-horizontal">
	{% if category.parent_category_id < 1 %}
		{{ text_area('ask_admin_text', 'placeholder' : 'Вопрос администратору', 'class' : 'form-control input-block', 'rows' : 7) }}
        <br>
		{{ link_to('./#', 'onclick' : 'return askAdmin();', 'text' : 'Отправить вопрос', 'type' : 'button', 'class' : 'btn btn-info') }}
		{{ link_to('./#', 'onclick' : '$("#ask_admin_div").hide(300); return false;', 'text' : 'Отмена', 'type' : 'button', 'class' : 'btn btn-info') }}
	{% endif %}
</div>


<?php if (count($category_child_cats)) { ?>

    <div>
        <?php if (strlen($category->rules) > 2) { ?>
        <div class="">
            <div class="title">Условия закупки</div>
            <div class="alert alert-info">{{ category.rules|e }}</div>
        </div>
        <br>
        <?php } ?>
        <div class="title">Закупки в категории &laquo;{{ category.title|e }}&raquo;</div><br>
        <table class="table table-bordered table-condensed cat_table">
            <tr>
                <td class="cat_title">Название и фото</td>
                <td class="cat_desc">Описание</td>
                <td class="cat_products_count">Товаров в закупке</td>
            </tr>
			{% for cur_category in category_child_cats %}
                <tr>
                    <td class="cat_title">
                        <div class="title">{{ cur_category.title }}</div>
                        <?=
                        $this->tag->linkTo(array(
                            '/categories/view/' . $cur_category->id,
                            'text' =>
							(strlen($cur_category->img) > 0 ? 
								('<img class="cat_img" src="data:image/jpeg;charset=utf-8;base64,' . $cur_category->img . '">') 
							:
							   	('<img class="cat_img" src="/img/noimage.jpg">'))));
                        ?>
                    </td>
                    <td class="cat_desc">{{cur_category.desc|e }}</td>
                    <td class="cat_products_count">
                        <?= Categories::productsCount($cur_category->id) ?>
                    </td>
                </tr>
			{% endfor %}
        </table>
    </div>

<?php } else { ?>

    <div>
        <?php if (strlen($category->rules) > 2) { ?>
        <div class="">
            <div class="title">Условия закупки</div>
            <div class="alert alert-info"><?= $category->rules ?></div>
        </div>
        <br>
        <?php } ?>
        <div class="title">Товары в закупке &laquo;<?= $category->title ?>&raquo;</div><br>
        <table class="table table-bordered table-condensed product_table">
            <?php $cur_index = 1; ?>
            <?php foreach ($this->view->products as $product) { ?>
                <tr>
                    <td style="width: 40px; vertical-align: middle; text-align: center" id="product_<?= $product->id ?>">
                        <?=
                        $this->tag->linkTo(array(
                            '/categories/view/' . $category->id . '#product_' . $product->id,
                            'text' => '' . $cur_index++,
                            'title' => 'Номер товара'
                        ));
                        ?>
                    </td>
                    <td class="product_title_text" style="vertical-align: middle; font-size: 0.75em ">
                        <div class="title">
                            <?=$this->tag->linkTo(array(
                            '/product/view/' . $product->id,
                            'text' => $product->title
                            ));
                        ?>
                        </div>
                    </td>
                    <td class="product_title">
                        <?php
                        if (file_exists(__DIR__ . '/../../../public/img/products/img_' . $category->id . '_' . $product->id . '.jpg')) {
                            $img_data = '/img/products/img_' . $category->id . '_' . $product->id . '.jpg';
                        } else {
                            $img_data = 'data:image/jpeg;charset=utf-8;base64,' . ProductImage::getProductImage($product->id);
                        }
                        if (file_exists(__DIR__ . '/../../../public/img/products/img_sm_' . $category->id . '_' . $product->id . '.jpg')) {
                            $small_img_data = '/img/products/img_sm_' . $category->id . '_' . $product->id . '.jpg';
                        } else {
                            $small_img_data = 'data:image/jpeg;charset=utf-8;base64,' . ProductImage::getProductImage($product->id);
                        }
                        ?>
                        <?php
                        echo (strlen($img_data) ?
                                ('<img class="cat_img prod_cat_img" src="' . $small_img_data . '" data-zoom-image="' . $img_data . '">') :
                                ('<img class="cat_img" src="/img/noimage.jpg">'))
                        ;
                        ?>
                    </td>
                    <td class="cat_desc"><?= $product->description ?></td>
                    <td class="product_price price"><?= $product->price ?></td>
                    <td><div>Размеры и заказы:</div>
                        <?php
                        $product_attributes = ProductAttribute::find(array(
                                    'conditions' => 'product_id = ?1',
                                    'bind' => array(
                                        1 => $product->id
                                    )
                        ));
                        ?>
                        <table class="table product_attributes_table">
                            <?php foreach ($product_attributes as $attr) : ?>
                                <tr>
                                    <td><?= $attr->attr ?></td>
                                    <td>
                                        <div>
                                        <?php
                                        if (!Categories::isStopped($product->category_id)) {
                                            echo $this->tag->linkTo(array(
                                                //'/product/order/' . $product->id . '/' . $attr->id,
                                                '#',
                                                'onclick' => 'return false;',
                                                'data-reveal-id' => 'orderModal_' . $product->id . '_' . $attr->id,
                                                'text' => 'Заказать',
                                                'class' => ''
                                            ));
                                            ?>
                                        </div>
                                        <div id="orderModal_<?= $product->id ?>_<?= $attr->id ?>" class="reveal-modal orderDialog" product_id="<?= $product->id ?>" attr_id="<?= $attr->id ?>">
                                            <h3>Сделать заказ</h3>
                                            <div class="err_block"></div>
                                            <label for="product_count">Количество: </label>{{ select_static('product_count', [1,2,3,4,5,6,7,8,9,10], 'class': 'product_count form-control') }}
                                            <label for="order_comment">Комментарий к заказу: </label>
                                            {{ text_area('order_comment', 'rows' : 3, 'class': 'order_comment form-control', 'placeholder' : 'комментарий не обязателен') }}
                                            <br>
                                            <div class="controls-row">
                                                <a href="#" onclick="makeOrder(this); return false;" class="btn btn-primary form-control">OK</a>
                                            </div>
                                            <a class="close-reveal-modal">&#215;</a>
                                        </div>
                                        <?php
                                        } else {
                                            echo $this->tag->linkTo(array(
                                                '#',
                                                'onclick' => 'return false;',
                                                'text' => 'Закупка завершена',
                                                'class' => ''
                                            ));
                                        }
                                        ?>
                                    </td>
                                    <td>
                                        <?php
                                        $ordered_users = SpOrder::find(array(
                                                    'conditions' => 'product_id = ?1 AND product_attr_id = ?2',
                                                    'bind' => array(
                                                        1 => $product->id,
                                                        2 => $attr->id
                                                    )
                                        ));
                                        ?>
                                        <?php foreach ($ordered_users as $cur_user) { ?>
                                            <div><?= User::getLogin($cur_user->user_id) ?></div>
                                        <?php } ?>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                        </table>
                    </td>
                </tr>
            <?php } ?>
        </table>
    </div>

<?php } ?>

{% if category.use_forum > 0 %}
	{{ form('/categories/new_message', 'id' : 'forum_new_message_form', 'class' : 'form-horizontal') }}
    <div class="forum_block" id="new_msg">
        <h3 class="help-block">Обсуждение закупки</h3>
        <div id="forum_new_msg">
            <table class="table">
                <tr>
                    <td style='width: 70px;'><label for="forum_new_msg_text">Сообщение:</label></td>
                    <td>{{ text_area("forum_new_msg_text", 'class' : 'form-control', 'rows' : 10) }}</td>
                </tr>
                <tr>
                    <td></td>
                    <td>
						{{ submit_button("Отправить", 'name' : 'forum_send_new_msg', 'class' : 'btn btn-default', 'onclick' : 'return check_forum_msg();') }}
						{{ hidden_field("category_id", 'value' : category.id) }}
                    </td>
                </tr>
            </table>
        </div>

        <table class="table table-condensed table-bordered forum_msgs_table">
			{% for cur_msg in forum_msgs %}
                <tr>
                    <td style="width: 40px;">
						{{ link_to('#' ~ cur_msg.id, 'text' : '#' ~ cur_msg.id, 'id' : cur_msg.id) }} 
                    </td>
                    <td class="forum_msg_info">
                        <span class="forum_info_user"><?= User::getLogin($cur_msg->user_id) ?></span>
                        <span class="forum_info_date">{{ cur_msg.item_datetime|rus_date(1) }}</span>
                    </td>
                    <td class="forum_msg_text">
                        <span class="">{{ cur_msg.msg }}</span>
                    </td>
                </tr>
			{% endfor %}
        </table>
    </div>
    </form>

{% endif %}

<script>
    <!--
    function check_forum_msg() {
        if ($.trim($('#forum_new_msg_text').val()) !== '') {
            return true;
        } else {
            $('#forum_new_msg_text').select();
            $('#forum_new_msg_text').focus();
            return false;
        }
    }
    
    function makeOrder(el) {
        var data = {
            product_id: $(el).parents('.orderDialog').attr('product_id'),
            attr_id: $(el).parents('.orderDialog').attr('attr_id'),
            product_count: $(el).parents('.orderDialog').find('.product_count option:selected').text(),
            info: $(el).parents('.orderDialog').find('.order_comment').val()
        };
        $.post('/product/order', data, function (retData) {
            var retObj = JSON.parse(retData);
                if (typeof retObj === 'object') {
                    if (retObj.hasError === true) {
                        $(el).parents('.orderDialog').find('.err_block').html(retObj.errorMsg).show();
                    } else {
                        location.reload();
                    }
                }
        });
        return false;
    }

    $('.prod_cat_img').elevateZoom({
        lensBorder: 0,
        zoomWindowWidth: 250,
        zoomWindowHeight: 200,
    });

    Zoomerang.config({
        maxHeight: 1024,
        maxWidth: 800,
        bgColor: '#000',
        bgOpacity: .85
    }).listen('.prod_cat_img');

<?php if ($category->parent_category_id < 1) { ?>
        function askAdmin() {
            $('#ask_admin_div').show(300);
            if ($('#ask_admin_div').is(':visible')) {
                var text = $.trim($('#ask_admin_text').val());
                if (text === '') {
                    $('#ask_admin_text').focus();
                    $('#ask_admin_text').select();
                    return false;
                }
                var data = {
                    id: <?= $category->id ?> + 0,
                    ask_admin: 1,
                    question: text
                };
                $.post('/categories/ask_admin', data, function(retData) {
                    var retObj = JSON.parse(retData);
                    if (typeof retObj === 'object') {
                        if (retObj.hasError === true) {
                            alert(retObj.errorMsg);
                        } else {
                            alert('Сообщение отправлено');
                            $('#ask_admin_div').hide(300);
                        }
                    }
                });
            }
            return false;
        }
<?php } ?>
-->
</script>
